name: Python build and test
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-activate-base: false
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Set up non-Windows dependencies
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          pip install -r ./tests/requirements.txt
          pip install -r requirements.txt
      - name: Set up Windows dependencies
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: |
          pip install -r ./tests/requirements.txt
          pip install -r requirements.txt
      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: ./cicd/run_tests.bat
      - name: Run tests on non-Windows
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: ./cicd/run_tests.sh
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          debug: true

# See: https://github.com/AndreMiras/coveralls-python-action
  coveralls_finish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: true
