name: Python build and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.9 ]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - uses: actions/checkout@v2
      - name: Setup environment on Windows
        if: matrix.os == 'windows-latest'
        run: ./cicd/setup_conda_env.bat
      - name: Setup environment on non-Windows
        if: matrix.os != 'windows-latest'
        run: |
          chmod 755 ./cicd/setup_conda_env.sh
          ./cicd/setup_conda_env.sh
      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        run: ./cicd/run_tests.bat
      - name: Run tests on non-Windows
        if: matrix.os != 'windows-latest'
        run: ./cicd/run_tests.sh
      - name: Tear down environment on Windows
        if: matrix.os == 'windows-latest'
        run: ./cicd/teardown_conda_env.bat
      - name: Tear down environment on non-Windows
        if: matrix.os != 'windows-latest'
        run: |
          chmod 755 ./cicd/teardown_conda_env.sh
          ./cicd/teardown_conda_env.sh
